/**
 * Curated from mubaic1004/exercises-dataset.
 * This catalogue intentionally contains metadata and original coaching copy only;
 * no image, GIF, or other media paths are included.
 */

export type MuscleId =
  | "chest"
  | "back"
  | "shoulders"
  | "arms"
  | "core"
  | "legs"
  | "glutes"
  | "full";

export type EquipmentId =
  | "bodyweight"
  | "dumbbell"
  | "barbell"
  | "cable"
  | "band"
  | "kettlebell";

export type Level = "beginner" | "intermediate";

export type ExerciseRole = "warmup" | "main" | "accessory" | "finisher";

export interface Exercise {
  id: string;
  sourceId: string;
  nameZh: string;
  nameEn: string;
  muscles: MuscleId[];
  equipment: EquipmentId;
  level: Level;
  role: ExerciseRole;
  movement: string;
  sets: number;
  reps: string;
  rest: number;
  minutes: number;
  instructions: string[];
}

export const EXERCISES: Exercise[] = [
  // Chest
  {
    id: "push-up",
    sourceId: "0662",
    nameZh: "俯卧撑",
    nameEn: "push-up",
    muscles: ["chest", "arms", "shoulders"],
    equipment: "bodyweight",
    level: "beginner",
    role: "main",
    movement: "水平推",
    sets: 3,
    reps: "8–15 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "双手略宽于肩，身体从头到脚保持一条直线。",
      "屈肘下降，直到胸口接近地面。",
      "胸肌发力推回，避免塌腰或耸肩。",
    ],
  },
  {
    id: "band-bench-press",
    sourceId: "1254",
    nameZh: "弹力带卧推",
    nameEn: "band bench press",
    muscles: ["chest", "arms", "shoulders"],
    equipment: "band",
    level: "beginner",
    role: "warmup",
    movement: "水平推",
    sets: 2,
    reps: "12–15 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "将弹力带固定在背后，仰卧并握稳两端。",
      "肩胛贴稳，双手向上推至手臂接近伸直。",
      "缓慢回落，始终保持弹力带张力。",
    ],
  },
  {
    id: "dumbbell-bench-press",
    sourceId: "0289",
    nameZh: "哑铃卧推",
    nameEn: "dumbbell bench press",
    muscles: ["chest", "arms", "shoulders"],
    equipment: "dumbbell",
    level: "beginner",
    role: "main",
    movement: "水平推",
    sets: 3,
    reps: "8–12 次",
    rest: 75,
    minutes: 7,
    instructions: [
      "仰卧在凳上，双脚踩稳，哑铃位于胸部两侧。",
      "向上推起哑铃，在胸口上方保持稳定。",
      "控制下降，肘部与身体约呈 45 度。",
    ],
  },
  {
    id: "dumbbell-incline-bench-press",
    sourceId: "0314",
    nameZh: "上斜哑铃卧推",
    nameEn: "dumbbell incline bench press",
    muscles: ["chest", "shoulders", "arms"],
    equipment: "dumbbell",
    level: "intermediate",
    role: "main",
    movement: "上斜推",
    sets: 3,
    reps: "8–12 次",
    rest: 75,
    minutes: 7,
    instructions: [
      "将训练凳调至约 30 度，肩胛向后下方收紧。",
      "从上胸两侧把哑铃推向上方。",
      "手腕保持中立，缓慢下降到舒适深度。",
    ],
  },
  {
    id: "barbell-bench-press",
    sourceId: "0025",
    nameZh: "杠铃卧推",
    nameEn: "barbell bench press",
    muscles: ["chest", "arms", "shoulders"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "水平推",
    sets: 4,
    reps: "6–10 次",
    rest: 90,
    minutes: 9,
    instructions: [
      "仰卧握杠略宽于肩，双脚和上背稳稳支撑。",
      "将杠铃控制下降至胸部中下方。",
      "沿原路径推起，手腕始终位于肘部上方。",
    ],
  },
  {
    id: "cable-standing-fly",
    sourceId: "0227",
    nameZh: "站姿绳索夹胸",
    nameEn: "cable standing fly",
    muscles: ["chest", "shoulders"],
    equipment: "cable",
    level: "intermediate",
    role: "accessory",
    movement: "水平内收",
    sets: 3,
    reps: "12–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "站在绳索架中央，身体微微前倾，双臂打开。",
      "保持肘部轻微弯曲，将手柄在胸前合拢。",
      "短暂停顿后控制还原，不要借力摆动。",
    ],
  },

  // Back
  {
    id: "pull-up",
    sourceId: "0652",
    nameZh: "引体向上",
    nameEn: "pull-up",
    muscles: ["back", "arms"],
    equipment: "bodyweight",
    level: "intermediate",
    role: "main",
    movement: "垂直拉",
    sets: 3,
    reps: "尽量完成 5–10 次",
    rest: 90,
    minutes: 7,
    instructions: [
      "正握单杠，先下沉肩胛并收紧核心。",
      "将胸口拉向单杠，避免摆腿借力。",
      "控制下降至手臂伸直，再开始下一次。",
    ],
  },
  {
    id: "dumbbell-one-arm-row",
    sourceId: "0292",
    nameZh: "单臂哑铃划船",
    nameEn: "dumbbell one arm bent-over row",
    muscles: ["back", "arms", "core"],
    equipment: "dumbbell",
    level: "beginner",
    role: "warmup",
    movement: "水平拉",
    sets: 2,
    reps: "每侧 12 次",
    rest: 30,
    minutes: 4,
    instructions: [
      "左手与左膝支撑训练凳，右脚踩稳，右手哑铃自然下垂。",
      "右肘贴近身体，将哑铃拉向右侧髋部。",
      "顶端收紧右侧背部，再控制放下；完成次数后换边。",
    ],
  },
  {
    id: "dumbbell-bent-over-row",
    sourceId: "0293",
    nameZh: "俯身哑铃划船",
    nameEn: "dumbbell bent over row",
    muscles: ["back", "arms", "core"],
    equipment: "dumbbell",
    level: "intermediate",
    role: "main",
    movement: "水平拉",
    sets: 3,
    reps: "8–12 次",
    rest: 75,
    minutes: 7,
    instructions: [
      "屈髋俯身，膝盖微屈，脊柱保持自然中立。",
      "双肘向后拉，把哑铃带向身体两侧。",
      "肩胛收紧后缓慢放下，躯干不要晃动。",
    ],
  },
  {
    id: "barbell-bent-over-row",
    sourceId: "0027",
    nameZh: "杠铃俯身划船",
    nameEn: "barbell bent over row",
    muscles: ["back", "arms", "core"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "水平拉",
    sets: 4,
    reps: "6–10 次",
    rest: 90,
    minutes: 9,
    instructions: [
      "屈髋俯身并收紧核心，让杠铃悬于膝下。",
      "肘部向后移动，将杠铃拉向下腹。",
      "背部保持平直，控制杠铃回到起点。",
    ],
  },
  {
    id: "cable-lat-pulldown",
    sourceId: "2330",
    nameZh: "高位下拉",
    nameEn: "cable lat pulldown full range of motion",
    muscles: ["back", "arms"],
    equipment: "cable",
    level: "beginner",
    role: "main",
    movement: "垂直拉",
    sets: 3,
    reps: "8–12 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "坐稳并握住横杆，胸口抬起，肩膀远离耳朵。",
      "肘部向下拉，将横杆带向上胸。",
      "缓慢伸直手臂，让背阔肌充分拉长。",
    ],
  },
  {
    id: "cable-seated-row",
    sourceId: "0861",
    nameZh: "坐姿绳索划船",
    nameEn: "cable seated row",
    muscles: ["back", "arms"],
    equipment: "cable",
    level: "beginner",
    role: "accessory",
    movement: "水平拉",
    sets: 3,
    reps: "10–15 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "坐直并踩稳踏板，手臂向前伸展。",
      "保持胸口抬起，把手柄拉向腹部。",
      "肩胛收拢后控制前送，避免含胸耸肩。",
    ],
  },

  // Shoulders
  {
    id: "dumbbell-standing-overhead-press",
    sourceId: "0426",
    nameZh: "站姿哑铃推举",
    nameEn: "dumbbell standing overhead press",
    muscles: ["shoulders", "arms", "core"],
    equipment: "dumbbell",
    level: "beginner",
    role: "main",
    movement: "垂直推",
    sets: 3,
    reps: "8–12 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "双脚与髋同宽，哑铃置于肩部两侧。",
      "收紧臀部和核心，将哑铃推至头顶。",
      "控制回到肩部，避免腰部过度后仰。",
    ],
  },
  {
    id: "dumbbell-lateral-raise",
    sourceId: "0334",
    nameZh: "哑铃侧平举",
    nameEn: "dumbbell lateral raise",
    muscles: ["shoulders"],
    equipment: "dumbbell",
    level: "beginner",
    role: "accessory",
    movement: "肩外展",
    sets: 3,
    reps: "12–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "哑铃置于身体两侧，肘部保持轻微弯曲。",
      "向两侧抬臂至接近肩高。",
      "缓慢下放，避免耸肩和身体摆动。",
    ],
  },
  {
    id: "dumbbell-rear-fly",
    sourceId: "0378",
    nameZh: "俯身哑铃反向飞鸟",
    nameEn: "dumbbell rear fly",
    muscles: ["shoulders", "back"],
    equipment: "dumbbell",
    level: "beginner",
    role: "warmup",
    movement: "水平外展",
    sets: 2,
    reps: "12–15 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "屈髋俯身，背部平直，双臂自然下垂。",
      "保持肘部微屈，将哑铃向两侧展开。",
      "后束三角肌收紧后缓慢回落。",
    ],
  },
  {
    id: "barbell-seated-overhead-press",
    sourceId: "0091",
    nameZh: "坐姿杠铃推举",
    nameEn: "barbell seated overhead press",
    muscles: ["shoulders", "arms"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "垂直推",
    sets: 4,
    reps: "6–10 次",
    rest: 90,
    minutes: 8,
    instructions: [
      "坐直并收紧核心，杠铃位于上胸前方。",
      "向上推举，让杠铃经过面部上方。",
      "手臂接近伸直后控制下放至起点。",
    ],
  },
  {
    id: "cable-seated-rear-lateral-raise",
    sourceId: "0215",
    nameZh: "坐姿绳索反向飞鸟",
    nameEn: "cable seated rear lateral raise",
    muscles: ["shoulders", "back"],
    equipment: "cable",
    level: "intermediate",
    role: "accessory",
    movement: "水平外展",
    sets: 3,
    reps: "12–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "坐姿交叉握住两侧绳索，躯干保持稳定。",
      "肩胛带动双臂向后外侧展开。",
      "顶端停顿，再控制绳索回到身前。",
    ],
  },
  {
    id: "band-shoulder-press",
    sourceId: "0997",
    nameZh: "弹力带肩上推举",
    nameEn: "band shoulder press",
    muscles: ["shoulders", "arms"],
    equipment: "band",
    level: "beginner",
    role: "warmup",
    movement: "垂直推",
    sets: 2,
    reps: "12–15 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "双脚踩住弹力带，将双手置于肩部两侧。",
      "收紧核心，把双手稳定推向头顶。",
      "缓慢回落，保持弹力带持续受力。",
    ],
  },

  // Arms
  {
    id: "dumbbell-biceps-curl",
    sourceId: "0294",
    nameZh: "哑铃弯举",
    nameEn: "dumbbell biceps curl",
    muscles: ["arms"],
    equipment: "dumbbell",
    level: "beginner",
    role: "main",
    movement: "肘屈",
    sets: 3,
    reps: "10–12 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "自然站立，掌心向前，肘部贴近身体。",
      "保持上臂不动，将哑铃弯举至肩前。",
      "顶端收紧肱二头肌，再缓慢下放。",
    ],
  },
  {
    id: "dumbbell-hammer-curl",
    sourceId: "0313",
    nameZh: "哑铃锤式弯举",
    nameEn: "dumbbell hammer curl",
    muscles: ["arms"],
    equipment: "dumbbell",
    level: "beginner",
    role: "accessory",
    movement: "中立握肘屈",
    sets: 3,
    reps: "10–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "掌心相对握住哑铃，肘部固定在身体两侧。",
      "保持中立握姿，将哑铃弯举到肩前。",
      "不甩动身体，控制哑铃回到起点。",
    ],
  },
  {
    id: "dumbbell-seated-triceps-extension",
    sourceId: "2188",
    nameZh: "坐姿哑铃臂屈伸",
    nameEn: "dumbbell seated triceps extension",
    muscles: ["arms", "shoulders"],
    equipment: "dumbbell",
    level: "beginner",
    role: "accessory",
    movement: "过顶肘伸",
    sets: 3,
    reps: "10–12 次",
    rest: 60,
    minutes: 5,
    instructions: [
      "坐直并双手托住哑铃，将其举到头顶。",
      "固定上臂，屈肘把哑铃降至脑后。",
      "肱三头肌发力伸肘，避免肘部外张。",
    ],
  },
  {
    id: "band-alternating-biceps-curl",
    sourceId: "0968",
    nameZh: "弹力带交替弯举",
    nameEn: "band alternating biceps curl",
    muscles: ["arms"],
    equipment: "band",
    level: "beginner",
    role: "warmup",
    movement: "交替肘屈",
    sets: 2,
    reps: "每侧 12 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "双脚踩住弹力带，两手握住两端。",
      "固定肘部，左右交替将手拉向肩部。",
      "全程控制回落，不让弹力带突然回弹。",
    ],
  },
  {
    id: "cable-triceps-pushdown",
    sourceId: "0241",
    nameZh: "绳索三头肌下压",
    nameEn: "cable triceps pushdown (v-bar)",
    muscles: ["arms"],
    equipment: "cable",
    level: "beginner",
    role: "accessory",
    movement: "肘伸",
    sets: 3,
    reps: "10–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "握住 V 形把手，肘部贴紧身体两侧。",
      "保持上臂不动，将把手压至手臂伸直。",
      "短暂停顿后控制回升，不要抬肩。",
    ],
  },
  {
    id: "close-grip-push-up",
    sourceId: "0259",
    nameZh: "窄距俯卧撑",
    nameEn: "close-grip push-up",
    muscles: ["arms", "chest", "shoulders"],
    equipment: "bodyweight",
    level: "intermediate",
    role: "finisher",
    movement: "窄距水平推",
    sets: 3,
    reps: "尽量完成 8–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "双手置于胸口下方，身体保持一条直线。",
      "肘部贴近躯干，缓慢降低身体。",
      "用肱三头肌和胸肌推回起点。",
    ],
  },

  // Core
  {
    id: "dead-bug",
    sourceId: "0276",
    nameZh: "死虫式",
    nameEn: "dead bug",
    muscles: ["core"],
    equipment: "bodyweight",
    level: "beginner",
    role: "warmup",
    movement: "抗伸展",
    sets: 2,
    reps: "每侧 8–10 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "仰卧抬起双臂和双腿，膝盖弯曲约 90 度。",
      "腰背贴地，同时伸展一侧手臂和对侧腿。",
      "回到中央后换边，始终保持核心收紧。",
    ],
  },
  {
    id: "air-bike",
    sourceId: "0003",
    nameZh: "自行车卷腹",
    nameEn: "air bike",
    muscles: ["core"],
    equipment: "bodyweight",
    level: "beginner",
    role: "accessory",
    movement: "旋转屈曲",
    sets: 3,
    reps: "每侧 12–16 次",
    rest: 30,
    minutes: 4,
    instructions: [
      "仰卧抬腿，双手轻放脑后，不要拉扯颈部。",
      "转动躯干，让一侧肘部靠近对侧膝盖。",
      "像踩单车一样交替伸腿，保持腰背稳定。",
    ],
  },
  {
    id: "reverse-crunch",
    sourceId: "0872",
    nameZh: "反向卷腹",
    nameEn: "reverse crunch",
    muscles: ["core"],
    equipment: "bodyweight",
    level: "beginner",
    role: "accessory",
    movement: "躯干屈曲",
    sets: 3,
    reps: "10–15 次",
    rest: 30,
    minutes: 4,
    instructions: [
      "仰卧并屈膝抬腿，双手放在身体两侧。",
      "收紧腹部，将骨盆卷向胸口并轻抬髋部。",
      "缓慢回落，避免用腿部惯性甩动。",
    ],
  },
  {
    id: "russian-twist",
    sourceId: "0687",
    nameZh: "俄罗斯转体",
    nameEn: "russian twist",
    muscles: ["core"],
    equipment: "bodyweight",
    level: "intermediate",
    role: "finisher",
    movement: "躯干旋转",
    sets: 3,
    reps: "每侧 12–20 次",
    rest: 30,
    minutes: 4,
    instructions: [
      "坐姿微微后倾，胸口抬起并收紧腹部。",
      "双手在胸前，从躯干带动向左右旋转。",
      "保持髋部稳定，不要只摆动手臂。",
    ],
  },
  {
    id: "front-plank-with-twist",
    sourceId: "0464",
    nameZh: "转体平板支撑",
    nameEn: "front plank with twist",
    muscles: ["core", "shoulders"],
    equipment: "bodyweight",
    level: "intermediate",
    role: "main",
    movement: "抗旋转",
    sets: 3,
    reps: "每侧 8–12 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "从前臂平板支撑开始，臀部与肩部保持稳定。",
      "收紧腹部，控制躯干向一侧转动。",
      "回到中央后换边，避免腰部塌陷。",
    ],
  },
  {
    id: "cable-kneeling-crunch",
    sourceId: "0175",
    nameZh: "跪姿绳索卷腹",
    nameEn: "cable kneeling crunch",
    muscles: ["core"],
    equipment: "cable",
    level: "intermediate",
    role: "main",
    movement: "负重躯干屈曲",
    sets: 3,
    reps: "10–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "背对或面向滑轮跪下，将绳索固定在头部两侧。",
      "髋部尽量稳定，用腹肌把胸口卷向膝盖。",
      "缓慢回到起点，不要用手臂向下拉。",
    ],
  },

  // Legs
  {
    id: "walking-lunge",
    sourceId: "1460",
    nameZh: "行走弓步",
    nameEn: "walking lunge",
    muscles: ["legs", "glutes", "core"],
    equipment: "bodyweight",
    level: "beginner",
    role: "warmup",
    movement: "弓步",
    sets: 2,
    reps: "每侧 10 步",
    rest: 30,
    minutes: 4,
    instructions: [
      "向前迈出适中一步，躯干保持直立。",
      "双膝弯曲下降，前脚全脚掌踩稳。",
      "前脚发力站起并连续迈向下一步。",
    ],
  },
  {
    id: "split-squats",
    sourceId: "2368",
    nameZh: "自重分腿蹲",
    nameEn: "split squats",
    muscles: ["legs", "glutes"],
    equipment: "bodyweight",
    level: "beginner",
    role: "accessory",
    movement: "单腿蹲",
    sets: 3,
    reps: "每侧 10–12 次",
    rest: 45,
    minutes: 6,
    instructions: [
      "前后分腿站立，重心保持在两脚之间。",
      "垂直下蹲，让后膝接近地面。",
      "前脚发力站起，膝盖始终朝向脚尖。",
    ],
  },
  {
    id: "dumbbell-goblet-squat",
    sourceId: "1760",
    nameZh: "哑铃高脚杯深蹲",
    nameEn: "dumbbell goblet squat",
    muscles: ["legs", "glutes", "core"],
    equipment: "dumbbell",
    level: "beginner",
    role: "main",
    movement: "深蹲",
    sets: 3,
    reps: "8–12 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "将哑铃竖直抱在胸前，双脚略宽于髋。",
      "髋膝同时弯曲下蹲，胸口保持抬起。",
      "脚掌踩地站起，膝盖与脚尖方向一致。",
    ],
  },
  {
    id: "barbell-full-squat",
    sourceId: "0043",
    nameZh: "杠铃深蹲",
    nameEn: "barbell full squat",
    muscles: ["legs", "glutes", "core"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "深蹲",
    sets: 4,
    reps: "6–10 次",
    rest: 90,
    minutes: 9,
    instructions: [
      "将杠铃稳放在上背，双脚约与肩同宽。",
      "收紧核心，髋膝同步弯曲下蹲。",
      "保持脚掌贴地，从中足发力站起。",
    ],
  },
  {
    id: "barbell-romanian-deadlift",
    sourceId: "0085",
    nameZh: "杠铃罗马尼亚硬拉",
    nameEn: "barbell romanian deadlift",
    muscles: ["legs", "glutes", "back"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "髋铰链",
    sets: 4,
    reps: "6–10 次",
    rest: 90,
    minutes: 9,
    instructions: [
      "站立握杠，膝盖微屈，肩胛和核心收紧。",
      "臀部向后推，让杠铃贴腿下降。",
      "感到大腿后侧拉伸后，夹紧臀部站起。",
    ],
  },
  {
    id: "bodyweight-standing-calf-raise",
    sourceId: "1373",
    nameZh: "自重站姿提踵",
    nameEn: "bodyweight standing calf raise",
    muscles: ["legs"],
    equipment: "bodyweight",
    level: "beginner",
    role: "finisher",
    movement: "踝跖屈",
    sets: 3,
    reps: "15–25 次",
    rest: 30,
    minutes: 4,
    instructions: [
      "站直并扶住稳定物体，双脚平行。",
      "脚趾踩地，将脚跟尽量抬高。",
      "顶端停顿后缓慢落下，保持身体稳定。",
    ],
  },

  // Glutes
  {
    id: "low-glute-bridge",
    sourceId: "3013",
    nameZh: "地面臀桥",
    nameEn: "low glute bridge on floor",
    muscles: ["glutes", "legs", "core"],
    equipment: "bodyweight",
    level: "beginner",
    role: "warmup",
    movement: "髋伸",
    sets: 2,
    reps: "12–15 次",
    rest: 30,
    minutes: 3,
    instructions: [
      "仰卧屈膝，双脚踩地并靠近臀部。",
      "收紧腹部和臀部，将髋部抬离地面。",
      "顶端不要过度挺腰，控制回落。",
    ],
  },
  {
    id: "barbell-glute-bridge",
    sourceId: "1409",
    nameZh: "杠铃臀桥",
    nameEn: "barbell glute bridge",
    muscles: ["glutes", "legs", "core"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "负重髋伸",
    sets: 4,
    reps: "8–12 次",
    rest: 75,
    minutes: 8,
    instructions: [
      "仰卧屈膝，将有护垫的杠铃稳放在髋部。",
      "脚跟踩地，臀部发力将髋部推高。",
      "顶端夹紧臀部，再控制杠铃回落。",
    ],
  },
  {
    id: "dumbbell-romanian-deadlift",
    sourceId: "1459",
    nameZh: "哑铃罗马尼亚硬拉",
    nameEn: "dumbbell romanian deadlift",
    muscles: ["glutes", "legs", "back"],
    equipment: "dumbbell",
    level: "intermediate",
    role: "main",
    movement: "髋铰链",
    sets: 3,
    reps: "8–12 次",
    rest: 75,
    minutes: 7,
    instructions: [
      "哑铃放在大腿前侧，膝盖保持微屈。",
      "臀部向后推，哑铃沿腿部缓慢下降。",
      "保持背部中立，臀部发力回到站姿。",
    ],
  },
  {
    id: "band-squat",
    sourceId: "1004",
    nameZh: "弹力带深蹲",
    nameEn: "band squat",
    muscles: ["glutes", "legs", "core"],
    equipment: "band",
    level: "beginner",
    role: "accessory",
    movement: "深蹲",
    sets: 3,
    reps: "12–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "双脚踩住弹力带，将两端固定在肩部。",
      "胸口抬起，髋膝同步弯曲下蹲。",
      "脚掌踩稳站起，顶端收紧臀部。",
    ],
  },
  {
    id: "band-kneeling-hip-thrust",
    sourceId: "3236",
    nameZh: "跪姿弹力带髋推",
    nameEn: "resistance band hip thrusts on knees (female)",
    muscles: ["glutes", "legs", "core"],
    equipment: "band",
    level: "beginner",
    role: "accessory",
    movement: "髋伸",
    sets: 3,
    reps: "12–15 次",
    rest: 45,
    minutes: 5,
    instructions: [
      "跪姿固定弹力带，让阻力横跨髋部。",
      "先将臀部向后坐，再用臀肌推动髋部向前。",
      "身体直立时夹紧臀部，避免腰部后仰。",
    ],
  },
  {
    id: "kettlebell-swing",
    sourceId: "0549",
    nameZh: "壶铃摆动",
    nameEn: "kettlebell swing",
    muscles: ["glutes", "legs", "core", "full"],
    equipment: "kettlebell",
    level: "intermediate",
    role: "finisher",
    movement: "爆发髋伸",
    sets: 4,
    reps: "15–20 次",
    rest: 45,
    minutes: 7,
    instructions: [
      "双手握壶铃，屈髋让壶铃摆到双腿之间。",
      "快速伸髋夹臀，让壶铃自然摆至胸前。",
      "手臂保持放松，顺势回到下一次髋铰链。",
    ],
  },

  // Full body
  {
    id: "burpee",
    sourceId: "1160",
    nameZh: "波比跳",
    nameEn: "burpee",
    muscles: ["full", "legs", "chest", "core"],
    equipment: "bodyweight",
    level: "intermediate",
    role: "finisher",
    movement: "全身爆发",
    sets: 3,
    reps: "8–12 次",
    rest: 45,
    minutes: 6,
    instructions: [
      "下蹲并将双手撑地，双脚向后跳成平板姿势。",
      "可完成一次俯卧撑，再将双脚跳回手旁。",
      "向上起跳并伸展身体，落地后立刻衔接。",
    ],
  },
  {
    id: "bear-crawl",
    sourceId: "3360",
    nameZh: "熊爬",
    nameEn: "bear crawl",
    muscles: ["full", "core", "shoulders", "legs"],
    equipment: "bodyweight",
    level: "beginner",
    role: "warmup",
    movement: "全身爬行",
    sets: 2,
    reps: "前后各 20 秒",
    rest: 30,
    minutes: 3,
    instructions: [
      "四点支撑，膝盖悬离地面，背部保持平直。",
      "对侧手脚同时小步向前移动。",
      "髋部保持低位，核心收紧并平稳呼吸。",
    ],
  },
  {
    id: "mountain-climber",
    sourceId: "0630",
    nameZh: "登山跑",
    nameEn: "mountain climber",
    muscles: ["full", "core", "legs", "shoulders"],
    equipment: "bodyweight",
    level: "beginner",
    role: "warmup",
    movement: "全身动态",
    sets: 3,
    reps: "30 秒",
    rest: 30,
    minutes: 4,
    instructions: [
      "从高位平板支撑开始，双手位于肩膀下方。",
      "左右交替将膝盖向胸口快速收回。",
      "保持肩髋稳定，避免臀部上下弹跳。",
    ],
  },
  {
    id: "dumbbell-burpee",
    sourceId: "1201",
    nameZh: "哑铃波比",
    nameEn: "dumbbell burpee",
    muscles: ["full", "legs", "chest", "core", "shoulders"],
    equipment: "dumbbell",
    level: "intermediate",
    role: "finisher",
    movement: "负重全身爆发",
    sets: 3,
    reps: "6–10 次",
    rest: 60,
    minutes: 6,
    instructions: [
      "双手握哑铃下蹲撑地，双脚向后跳。",
      "保持哑铃稳定，可完成一次俯卧撑。",
      "双脚跳回后站起，动作全程控制落地。",
    ],
  },
  {
    id: "barbell-clean-and-press",
    sourceId: "0028",
    nameZh: "杠铃翻举推举",
    nameEn: "barbell clean and press",
    muscles: ["full", "legs", "glutes", "shoulders", "arms"],
    equipment: "barbell",
    level: "intermediate",
    role: "main",
    movement: "拉起与垂直推",
    sets: 4,
    reps: "4–6 次",
    rest: 120,
    minutes: 10,
    instructions: [
      "从地面以平直背部拉起杠铃，贴近身体加速。",
      "快速翻腕接杠至肩前，屈膝缓冲并站稳。",
      "收紧核心将杠铃推过头顶，再控制放下。",
    ],
  },
  {
    id: "kettlebell-one-arm-clean-and-jerk",
    sourceId: "0537",
    nameZh: "单臂壶铃翻举挺举",
    nameEn: "kettlebell one arm clean and jerk",
    muscles: ["full", "glutes", "legs", "shoulders", "arms"],
    equipment: "kettlebell",
    level: "intermediate",
    role: "main",
    movement: "髋爆发与垂直推",
    sets: 3,
    reps: "每侧 6–8 次",
    rest: 75,
    minutes: 8,
    instructions: [
      "用髋部发力将壶铃翻至肩前架式位置。",
      "轻微屈膝蓄力，再快速伸展把壶铃送过头顶。",
      "稳定锁定后控制回到肩前，完成一侧再换边。",
    ],
  },
];
